/*
   The commands below can be used to rebuild the indexes on versioned tables, such as in the 
   CED3_DEVL workspace.
*/   

exec dbms_wm.alterversionedtable('CATEGORY_SETS','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CATEGORY_SETS_PKI$');
exec dbms_wm.alterversionedtable('CATEGORY_SETS','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CATEGORY_SETS_TI$');
exec dbms_wm.alterversionedtable('CATEGORY_SETS','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XAK1CATEGORY_SETS');
exec dbms_wm.alterversionedtable('CMPNT','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_PKI$');
exec dbms_wm.alterversionedtable('CMPNT','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_TI$');
exec dbms_wm.alterversionedtable('CMPNT','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XAK1CMPNT_NAME');
exec dbms_wm.alterversionedtable('CMPNT','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XAK1CMPNT_NAME_UP');
exec dbms_wm.alterversionedtable('CMPNT','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIF1CMPNT');
exec dbms_wm.alterversionedtable('CMPNT','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XPKCMPNT');
exec dbms_wm.alterversionedtable('CMPNT_OWNERS','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_OWNERS_PKI$');
exec dbms_wm.alterversionedtable('CMPNT_OWNERS','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_OWNERS_TI$');
exec dbms_wm.alterversionedtable('CMPNT_OWNERS','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XPKCMPNT_OWNERS');
exec dbms_wm.alterversionedtable('CMPNT_PROP_BLOB','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_PROP_BLOB_PKI$');
exec dbms_wm.alterversionedtable('CMPNT_PROP_BLOB','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_PROP_BLOB_TI$');
exec dbms_wm.alterversionedtable('CMPNT_PROP_BLOB','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIF2CMPNT_PROP_BLOB');
exec dbms_wm.alterversionedtable('CMPNT_PROP_BLOB','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XPKCMPNT_PROP_BLOB');
exec dbms_wm.alterversionedtable('CMPNT_PROP_BLOB','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=AUX_CMPNT_PROP_BOOL');
exec dbms_wm.alterversionedtable('CMPNT_PROP_BOOL','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_PROP_BOOL_PKI$');
exec dbms_wm.alterversionedtable('CMPNT_PROP_BOOL','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_PROP_BOOL_TI$');
exec dbms_wm.alterversionedtable('CMPNT_PROP_BOOL','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIE1CMPNT_PROP_BOOL');
exec dbms_wm.alterversionedtable('CMPNT_PROP_BOOL','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIF2CMPNT_PROP_BOOL');
exec dbms_wm.alterversionedtable('CMPNT_PROP_BOOL','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XPKCMPNT_PROP_BOOL');
exec dbms_wm.alterversionedtable('CMPNT_PROP_DATE','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=AUX_CMPNT_PROP_DATE');
exec dbms_wm.alterversionedtable('CMPNT_PROP_DATE','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_PROP_DATE_AP1$');
exec dbms_wm.alterversionedtable('CMPNT_PROP_DATE','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_PROP_DATE_AP2$');
exec dbms_wm.alterversionedtable('CMPNT_PROP_DATE','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_PROP_DATE_PKI$');
exec dbms_wm.alterversionedtable('CMPNT_PROP_DATE','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_PROP_DATE_TI$');
exec dbms_wm.alterversionedtable('CMPNT_PROP_DATE','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIE1CMPNT_PROP_DATE');
exec dbms_wm.alterversionedtable('CMPNT_PROP_DATE','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIF2CMPNT_PROP_DATE');
exec dbms_wm.alterversionedtable('CMPNT_PROP_FK_CMPNT','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XPKCMPNT_PROP_DATE');
exec dbms_wm.alterversionedtable('CMPNT_PROP_FK_CMPNT','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=AUX_CMPNT_PROP_FK_CMPNT');
exec dbms_wm.alterversionedtable('CMPNT_PROP_FK_CMPNT','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_PROP_FK_CMPNT_AP1$');
exec dbms_wm.alterversionedtable('CMPNT_PROP_FK_CMPNT','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_PROP_FK_CMPNT_AP2$');
exec dbms_wm.alterversionedtable('CMPNT_PROP_FK_CMPNT','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_PROP_FK_CMPNT_PKI$');
exec dbms_wm.alterversionedtable('CMPNT_PROP_FK_CMPNT','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_PROP_FK_CMPNT_TI$');
exec dbms_wm.alterversionedtable('CMPNT_PROP_FK_CMPNT','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIE1CMPNT_PROP_FK_CMPNT');
exec dbms_wm.alterversionedtable('CMPNT_PROP_FK_CMPNT','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIF2CMPNT_PROP_FK_CMPNT');
exec dbms_wm.alterversionedtable('CMPNT_PROP_FK_CMPNT','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XPKCMPNT_PROP_FK_CMPNT');
exec dbms_wm.alterversionedtable('CMPNT_PROP_FLOAT','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=AUX_CMPNT_PROP_FLOAT');
exec dbms_wm.alterversionedtable('CMPNT_PROP_FLOAT','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_PROP_FLOAT_AP1$');
exec dbms_wm.alterversionedtable('CMPNT_PROP_FLOAT','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_PROP_FLOAT_AP2$');
exec dbms_wm.alterversionedtable('CMPNT_PROP_FLOAT','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_PROP_FLOAT_PKI$');
exec dbms_wm.alterversionedtable('CMPNT_PROP_FLOAT','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_PROP_FLOAT_TI$');
exec dbms_wm.alterversionedtable('CMPNT_PROP_FLOAT','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIE1CMPNT_PROP_FLOAT');
exec dbms_wm.alterversionedtable('CMPNT_PROP_FLOAT','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIF2CMPNT_PROP_FLOAT');
exec dbms_wm.alterversionedtable('CMPNT_PROP_FLOAT','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XPKCMPNT_PROP_FLOAT');
exec dbms_wm.alterversionedtable('CMPNT_PROP_INTEGER','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=AUX_CMPNT_PROP_INTEGER');
exec dbms_wm.alterversionedtable('CMPNT_PROP_INTEGER','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_PROP_INTEGER_AP1$');
exec dbms_wm.alterversionedtable('CMPNT_PROP_INTEGER','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_PROP_INTEGER_AP2$');
exec dbms_wm.alterversionedtable('CMPNT_PROP_INTEGER','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_PROP_INTEGER_PKI$');
exec dbms_wm.alterversionedtable('CMPNT_PROP_INTEGER','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_PROP_INTEGER_TI$');
exec dbms_wm.alterversionedtable('CMPNT_PROP_INTEGER','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIE1CMPNT_PROP_INTEGER');
exec dbms_wm.alterversionedtable('CMPNT_PROP_INTEGER','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIF2CMPNT_PROP_INTEGER');
exec dbms_wm.alterversionedtable('CMPNT_PROP_INTEGER','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XPKCMPNT_PROP_INTEGER');
exec dbms_wm.alterversionedtable('CMPNT_PROP','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_PROP_PKI$');
exec dbms_wm.alterversionedtable('CMPNT_PROP','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_PROP_TI$');
exec dbms_wm.alterversionedtable('CMPNT_PROP','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIE1CMPNT_PROP');
exec dbms_wm.alterversionedtable('CMPNT_PROP','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIF2CMPNT_PROP');
exec dbms_wm.alterversionedtable('CMPNT_PROP','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIF3CMPNT_PROP');
exec dbms_wm.alterversionedtable('CMPNT_PROP','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XPKCMPNT_PROP');
exec dbms_wm.alterversionedtable('CMPNT_PROP_STRING','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=AUX_CMPNT_PROP_STRING');
exec dbms_wm.alterversionedtable('CMPNT_PROP_STRING','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_PROP_STRING_AP1$');
exec dbms_wm.alterversionedtable('CMPNT_PROP_STRING','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_PROP_STRING_AP2$');
exec dbms_wm.alterversionedtable('CMPNT_PROP_STRING','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_PROP_STRING_PKI$');
exec dbms_wm.alterversionedtable('CMPNT_PROP_STRING','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_PROP_STRING_TI$');
exec dbms_wm.alterversionedtable('CMPNT_PROP_STRING','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIE1CMPNT_PROP_STRING');
exec dbms_wm.alterversionedtable('CMPNT_PROP_STRING','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIF2CMPNT_PROP_STRING');
exec dbms_wm.alterversionedtable('CMPNT_PROP_STRING','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XPKCMPNT_PROP_STRING');
exec dbms_wm.alterversionedtable('CMPNT_TYPE','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=AUX_CMPNT_TYPE');
exec dbms_wm.alterversionedtable('CMPNT_TYPE','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_TYPE_AP1$');
exec dbms_wm.alterversionedtable('CMPNT_TYPE','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_TYPE_AP2$');
exec dbms_wm.alterversionedtable('CMPNT_TYPE','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XAK1CMPNT_TYPE_LCK');
exec dbms_wm.alterversionedtable('CMPNT_TYPE','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XAK1CMPNT_TYPE_UP_LCK');
exec dbms_wm.alterversionedtable('CMPNT_TYPE','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_TYPE_PKI$');
exec dbms_wm.alterversionedtable('CMPNT_TYPE','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_TYPE_TI$');
exec dbms_wm.alterversionedtable('CMPNT_TYPE','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XAK1CMPNT_TYPE');
exec dbms_wm.alterversionedtable('CMPNT_TYPE','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XAK1CMPNT_TYPE_UP');
exec dbms_wm.alterversionedtable('CMPNT_TYPE','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIF1CMPNT_TYPE');
exec dbms_wm.alterversionedtable('CMPNT_TYPE','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XPKCMPNT_TYPE');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_OWNERS','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_TYPE_OWNERS_PKI$');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_OWNERS','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_TYPE_OWNERS_TI$');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_OWNERS','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XPKCMPNT_TYPE_OWNERS');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=AUX_CMPNT_TYPE_PROP');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_TYPE_PROP_AP1$');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_TYPE_PROP_AP2$');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP_CATS','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XAK1PROP_CATS_LCK');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP_CATS','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_TYPE_PROP_CATS_PKI$');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP_CATS','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_TYPE_PROP_CATS_TI$');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP_CATS','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XAK1PROP_CATS');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP_CATS','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIF1PROP_CATS');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP_CATS','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XPKPROP_CATS');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP_DEF','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_TYPE_PROP_DEF_PKI$');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP_DEF','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_TYPE_PROP_DEF_TI$');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP_DEF','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIF1CMPNT_TYPE_PROP_DEFAULT');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP_DEF','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIF2CMPNT_TYPE_PROP_DEFAULT');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP_DEF','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XPKCMPNT_TYPE_PROP_DEFAULT');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP_DIM','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_TYPE_PROP_DIM_PKI$');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP_DIM','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_TYPE_PROP_DIM_TI$');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP_DIM','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIF1CMPNT_TYPE_PROP_DIM');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP_DIM','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIF2CMPNT_TYPE_PROP_DIM');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP_DIM','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XPKCMPNT_TYPE_PROP_DIM');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP_DOM','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_TYPE_PROP_DOM_PKI$');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP_DOM','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_TYPE_PROP_DOM_TI$');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP_DOM','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIF1CMPNT_TYPE_PROP_DOM');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP_DOM','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIF2CMPNT_TYPE_PROP_DOM');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP_DOM','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XPKCMPNT_TYPE_PROP_DOM');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_TYPE_PROP_PKI$');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_TYPE_PROP_TI$');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XAK1CMPNT_TYPE_PROP_NAME');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIF1CMPNT_TYPE_PROP');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIF2CMPNT_TYPE_PROP');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XPKCMPNT_TYPE_PROP');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP_REQ','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_TYPE_PROP_REQ_PKI$');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP_REQ','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=CMPNT_TYPE_PROP_REQ_TI$');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP_REQ','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIF1CMPNT_TYPE_PROP_REQ');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP_REQ','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIF2CMPNT_TYPE_PROP_REQ');
exec dbms_wm.alterversionedtable('CMPNT_TYPE_PROP_REQ','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XPKCMPNT_TYPE_PROP_REQ');
exec dbms_wm.alterversionedtable('SEGMENTS','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=SEGMENTS_PKI$');
exec dbms_wm.alterversionedtable('SEGMENTS','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=SEGMENTS_TI$');
exec dbms_wm.alterversionedtable('SEGMENTS','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIF1ZONES');
exec dbms_wm.alterversionedtable('SEGMENTS','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIF2ZONES');
exec dbms_wm.alterversionedtable('SEGMENTS','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIF3ZONES');
exec dbms_wm.alterversionedtable('SEGMENTS','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XPKSEGMENTS');
exec dbms_wm.alterversionedtable('ZONES','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XAK1ZONES');
exec dbms_wm.alterversionedtable('ZONES','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XAK1ZONE_NAME_UP');
exec dbms_wm.alterversionedtable('ZONES','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XPKZONES');
exec dbms_wm.alterversionedtable('ZONES','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=ZONES_PKI$');
exec dbms_wm.alterversionedtable('ZONES','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=ZONES_TI$');
exec dbms_wm.alterversionedtable('ZONE_LINKS','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIF1ZONE_LINKS');
exec dbms_wm.alterversionedtable('ZONE_LINKS','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XIF2ZONE_LINKS');
exec dbms_wm.alterversionedtable('ZONE_LINKS','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=XPKZONE_LINKS');
exec dbms_wm.alterversionedtable('ZONE_LINKS','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=ZONE_LINKS_PKI$');
exec dbms_wm.alterversionedtable('ZONE_LINKS','REBUILD_INDEX','index_owner=CED3_DEVL, index_name=ZONE_LINKS_TI$');




EXECUTE DBMS_STATS.GATHER_TABLE_STATS('','CATEGORY_SETS_LT');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('','CMPNT_LT');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('','CMPNT_OWNERS_LT');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('','CMPNT_PROP_BLOB_LT');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('','CMPNT_PROP_BOOL_LT');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('','CMPNT_PROP_DATE_LT');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('','CMPNT_PROP_FK_CMPNT_LT');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('','CMPNT_PROP_FLOAT_LT');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('','CMPNT_PROP_INTEGER_LT');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('','CMPNT_PROP_LT');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('','CMPNT_PROP_STRING_LT');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('','CMPNT_TYPE_LT');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('','CMPNT_TYPE_OWNERS_LT');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('','CMPNT_TYPE_PROP_CATS_LT');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('','CMPNT_TYPE_PROP_DEF_LT');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('','CMPNT_TYPE_PROP_DIM_LT');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('','CMPNT_TYPE_PROP_MIX_LT');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('','CMPNT_TYPE_PROP_DOM_LT');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('','CMPNT_TYPE_PROP_LT');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('','CMPNT_TYPE_PROP_OWNERS_LT');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('','CMPNT_TYPE_PROP_REQ_LT');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('','SEGMENTS_LT');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('','ZONES_LT');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS('','ZONE_LINKS_LT');






